### ISSUE TITLE
Links to loot

### ISSUE THREAD

**Issue by 3zcurdia** [BirdPersonInc/birdpersoninc.github.io#10]
on **_config.yml** add urls for downloadables

### Example
```yaml
download:
  source:           "https://github.com/twbs/bootstrap/archive/v4.0.0.zip"
  dist:             "https://github.com/twbs/bootstrap/releases/download/v4.0.0/bootstrap-4.0.0-dist.zip"
```
